version: "2.2"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - 4444:4444

  app:
    image: budtmo/docker-android-x86-10.0
    privileged: true
    #scale if needed, the topic with the ports would be interesting
    scale: 1
    depends_on:
      - selenium_hub
    ports:
      - 6080
      - 5554
      - 5555
    volumes:
      - /home/ec2-user/apks:/apks
    environment:
      - DEVICE=Samsung Galaxy S10
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      #- AUTO_RECORD=true

#if necessary we can stream the logs to cloudwatch https://docs.docker.com/config/containers/logging/awslogs/